Repository ironcore-dev/machine-controller-manager-provider-ironcore-metal, pull requests merged in 2025-03, with the labels that each got.

#69 Ignore NoMatchError on IP deletion
  pkg/metal/delete_machine.go
Labels: size/XS, provider

#67 Use k8s atomic writer to test client provider
  go.mod
  go.sum
  pkg/client/provider_test.go
  pkg/client/suite_test.go
Labels: enhancement, size/L

#74 Update reuse configuration
  REUSE.toml
Labels: size/S, chore

#46 Bump `k8s.io/*` to v0.32
  .github/workflows/lint.yml
  Makefile
  go.mod
  go.sum
  pkg/metal/create_machine.go
  pkg/metal/suite_test.go
Labels: enhancement, provider, size/M

#75 Allow multiple IPAM configs for CAPI
  pkg/metal/create_machine.go
  pkg/metal/create_machine_test.go
  pkg/metal/delete_machine.go
  pkg/metal/delete_machine_test.go
  pkg/metal/suite_test.go
Labels: enhancement, provider, size/L

#80 Remove support for ironcore `ipam`
  go.mod
  go.sum
  pkg/client/provider.go
  pkg/metal/create_machine.go
  pkg/metal/delete_machine.go
  pkg/metal/suite_test.go
Labels: enhancement, provider, size/M

#82 Remove `CSIDriverName`
  cmd/machine-controller/main.go
  pkg/metal/driver.go
  pkg/metal/suite_test.go
Labels: size/XS, provider, chore
