Repository ironcore-dev/machine-controller-manager-provider-ironcore-metal, pull requests merged in 2025-02, with the labels that each got.

#53 Wait always for IP address to become ready
  pkg/metal/create_machine.go
Labels: provider, size/M

#54 Exit wait context if there is no `IP` object
  pkg/metal/create_machine.go
Labels: provider, size/S

#44 Reload metal-kubeconfig
  cmd/machine-controller/main.go
  go.mod
  go.sum
  pkg/client/provider.go
  pkg/client/provider_test.go
  pkg/metal/create_machine.go
  pkg/metal/delete_machine.go
  pkg/metal/driver.go
  pkg/metal/get_machine_status.go
  pkg/metal/list_machines.go
  pkg/metal/suite_test.go
Labels: provider, size/L

#50 Add support for capi ipam
  go.mod
  go.sum
  pkg/client/provider.go
  pkg/metal/create_machine.go
  pkg/metal/delete_machine.go
  pkg/metal/suite_test.go
Labels: enhancement, provider, size/L

#55 Fix IPAddressClaim PoolRef kind
  pkg/metal/create_machine.go
Labels: enhancement, size/XS, provider

#59 Add logs to client provider
  pkg/client/provider.go
Labels: size/S

#60 Fix klog version
  go.mod
  go.sum
  pkg/client/provider.go
  pkg/metal/create_machine.go
Labels: bug, size/XS, provider

#62 Add `prefix` and `gateway` to capi ipam metadata
  pkg/metal/create_machine.go
Labels: bug, enhancement, size/XS, provider

#63 Remove overwriting of log flags
  cmd/machine-controller/main.go
Labels: size/XS

#65 Check target file changes in client provider
  pkg/client/provider.go
Labels: size/S

#66 Set logger for the controller runtime
  pkg/client/provider.go
Labels: size/XS
